### ISSUE TITLE
errors while reindexing

### ISSUE THREAD

**Issue by vutuong** [Intsights/fast_elasticsearch_reindex#1]
Hello, I'm trying to use your source to reindex about 20G of my data from remote cluster to local cluster. It's not really an errors but I found that there is 1/3 of the docs reported as errors while the reindexer is operating. So I wonder that it means these doc will not reindex and lost, right? It's so frustrated since I have to wait for a very long time but can not reindex full of my data. Thanks.

**Comment by asonn-r7** [comment]
Hello @vutuong. This repository is not under maintenance right now.
